src/pilot/install-director.sh

added test to abort the director install if customized overcloud... 

---

src/deploy/osp_deployer/checkpoints.py
src/deploy/osp_deployer/director.py
src/deploy/osp_deployer/profiles/csp.json
src/deploy/osp_deployer/profiles/xsp.json
src/deploy/osp_deployer/sah.py
src/deploy/osp_deployer/settings/config.py
src/deploy/osp_deployer/settings/sample_csp_profile.ini
src/deploy/osp_deployer/settings/sample_xsp_profile.ini
src/deploy/osp_deployer/settings_sanity.py
src/pilot/deploy-overcloud.py
src/pilot/templates/network-environment.yaml
src/pilot/templates/nic-configs/4_port/compute.yaml
src/pilot/templates/nic-configs/4_port/controller.yaml
src/pilot/templates/nic-configs/4_port/nic_environment.yaml
src/pilot/templates/nic-configs/4_port/storage.yaml
src/pilot/templates/nic-configs/5_port/compute.yaml
src/pilot/templates/nic-configs/5_port/controller.yaml
src/pilot/templates/nic-configs/5_port/nic_environment.yaml
src/pilot/templates/nic-configs/5_port/storage.yaml

This patch adds the NIC configuration files for 25G NICs.  It also changes the
NIC config infrastructure so that new NIC configurations can be added without
making any code changes.

NIC configuration for 25G NICs

---

src/deploy/osp_deployer/profiles/csp.json

The valid hpg sizes are 2MB and 1GB.

Fixed the valid hpg sizes

---

src/deploy/osp_deployer/sah.py
src/mgmt/osp-sah.ks

This patch allows the user to optionally specify an anaconda interface
that has a .vlanid suffix.

25g support: anaconda vlan support

---

src/pilot/assign_role.py

This patch contains fixes to support a RAID controller in an R740xd.  Two
fixes are included:
- Correctly detect PERC H740P RAID controllers
- Only attempt to convert disks to JBOD and RAID mode if they're attached to a
RAID controller.  This allows drives controlled by non-RAID controllers to
be present in the servers.

Fixes to support a RAID controller in an R740xd

---

src/deploy/osp_deployer/director.py
src/deploy/osp_deployer/profile.py
src/deploy/osp_deployer/settings_sanity.py
src/deploy/setup/setup_usb_idrac.py
src/mgmt/deploy-dashboard-vm.py
src/pilot/config_dashboard.py
src/pilot/deploy-overcloud.py
src/pilot/network-validation/validate_networks.py

PEP8 fixes

---

src/pilot/assign_role.py

This patch changes our RAID configuration to handle the case where there is a RAID controller and NVMe drives.  It:
1. On controller and compute nodes, if only 3 drives are present, it create a 3 legged RAID1
2. On storage nodes, strategy 1 now handles the case where there are no spinning drives present
3. Error handling for storage nodes is changed so that there must be at least 2 drives connected to the RAID controller and there must be at least 1 free drive (either connected to the RAID controller or not (NVMe)) for OSD/journal configuration

Adding RAID support for the NVMe drive configuration

---

src/deploy/osp_deployer/deployer.py
src/deploy/osp_deployer/director.py
src/deploy/osp_deployer/profiles/csp.json
src/deploy/osp_deployer/profiles/xsp.json
src/deploy/osp_deployer/settings/config.py
src/deploy/osp_deployer/settings/sample_csp_profile.ini
src/deploy/osp_deployer/settings/sample_xsp_profile.ini
src/pilot/cpu_siblings.py
src/pilot/dell_nfv.py
src/pilot/deploy-overcloud.py
src/pilot/templates/create_aggregate_environment.yaml
src/pilot/templates/dellnfv/createaggregate.yaml

@cdearborn @jproque-dell @gaelrehault

Numa Hugepage Enhancement

---

src/pilot/config_dashboard.py
src/pilot/customize_image.sh

... fix permissions on ceph.client.openstack.keyring file

2 issues combined -- no need for calamari-server rpm package and ... 

---

src/pilot/assign_role.py

This fix gracefully handles the list index erros for any raid controller list components.

Fix bug CES-7679

---

src/update_upgrade/update-js10.2.0.sh

Tested and verified on Red stamp twice, with version
locking off and on.

Refactor to work with latest bits

---

src/deploy/osp_deployer/settings/sample_csp_profile.ini
src/deploy/osp_deployer/settings/sample_xsp_profile.ini

This PR is about changing references from 13G to 14G servers.
We are expecting the interfaces to remain on the same slot than for 13G.

CES-9514 - Changing reference from 13G to 14G servers.

---

src/pilot/cpu_siblings.py
src/pilot/dell_nfv.py
src/pilot/deploy-overcloud.py
src/pilot/templates/first-boot-ovs-dpdk.yaml
src/pilot/templates/neutron-ovs-dpdk.yaml

@cdearborn @gaelrehault @jproque-dell

CES-9561 & CES-9562 FIX

---

src/mgmt/deploy-director-vm.sh

CES-9058 -- Updated code and templates with latest supported RHEL ... 

---

src/deploy/osp_deployer/profiles/csp.json

@jproque-dell @gaelrehault @cdearborn

Fix for CES-9569 & CES-9570

---

src/pilot/templates/nic-configs/dpdk_mode1_5_port/compute-ovs-dpdk-mode1.yaml
src/pilot/templates/nic-configs/dpdk_mode2_5_port/compute-ovs-dpdk-mode2.yaml

- Arranged OVS bridges and interfaces in proper order.
- Fixed Linux bonds and interfaces.

DPDK 5 port fix for bug 9576

---

src/deploy/osp_deployer/settings/sample_csp_profile.ini
src/deploy/osp_deployer/settings/sample_xsp_profile.ini

Fix for CES-9601: 4 port nic setup needs provisioning nic option disabled

Fix for CES-9601

---

src/deploy/osp_deployer/director.py
src/pilot/templates/static-ip-environment.yaml

fixed compute nodes getting DHCP address when static ip's were set in .properties

CES-9577 - fixed compute nodes getting DHCP i/o static

---

src/deploy/osp_deployer/settings/sample_csp_profile.ini
src/deploy/osp_deployer/settings/sample_xsp_profile.ini

Updated hugepages ini file changes for bug CES-9596

FIX CES-9596 updated comment for number of hugepages in csp_ini file

---

src/deploy/osp_deployer/director.py
src/pilot/templates/static-ip-environment.yaml

Removed the CHANGEME's and sample IPs from the NovaCompute section of static-ip-environment.yaml.
Updated the automation code so it won't substitute IPs into the NovaCompute section.

ces-9624: static-ips.yaml has both DellCompute and NovaCompute sections

---

src/deploy/osp_deployer/profile.py

This just adds a space between sentences.

Part of the fix for ces-9325

---

src/deploy/osp_deployer/settings/sample_csp_profile.ini
src/deploy/osp_deployer/settings/sample_xsp_profile.ini

Eliminated differences between .ini files

---

src/update_upgrade/9490d69.diff
src/update_upgrade/update-js10.2.0.sh

Both of these patches fix update, otherwise
upate will fail.
Fixes: CES-9644, CES-9630

Patch roles_data.yaml and current_config_hosts.rb

---

src/update_upgrade/update-js10.2.0.sh

When I created the patch support had not yet
created a BZ so I left a place holder for it.
Added link to actual BZ in comment.

Added ref BZ as it was not available originally

---

README.md

Added link to jetstream 10.2 deployment guide on Dell tech center website.

Added link to jetstream 10.2 deployment guide on Dell tech center website

---

src/pilot/ironic_helper.py

- Removed duplicate ironic api parameter
- Fixed pep8 warning

Removed duplicate ironic api parameter

---

src/pilot/deployment-validation/sanity.ini
src/pilot/deployment-validation/sanity_test.sh

- All the resources except public network are created with sanity user now.
- A trunk is created with parent and sub-port which is attached to the VM to make it VLAN aware.
- The tagged interface of the VM is pinged from the controller.

Sanity check added for VLAN aware VM.

---

src/pilot/import_nodes.py

Deleted a print statement with a misspelling that snuck in somehow.

Deleted a print statement with a misspelling

---

src/pilot/dell_nfv.py
src/pilot/deploy-overcloud.py

removed references to removed nova module

---

src/deploy/osp_deployer/settings/config.py
src/deploy/osp_deployer/settings/sample_csp_profile.ini
src/deploy/osp_deployer/settings/sample_xsp_profile.ini
src/mgmt/deploy-director-vm.sh

... to pick up ceph-ansible-3.1.5-1

added new ceph repo ..

---

src/deploy/osp_deployer/deployer.py
src/deploy/osp_deployer/director.py
src/pilot/install-director.sh

This PR merges master into the experimental_upstream_ironic branch.

Sync with master

---

src/pilot/client.patch
src/pilot/idrac_card.patch
src/pilot/install-director.sh

This PR monkey patches iDRAC reset into the currently shipping z3 release of OSP13.  When z4 comes out, these changes should be rolled back.

Monkey patch upstream iDRAC reset feature into z3

---

src/pilot/config_idrac.py
src/pilot/discover_nodes/discover_nodes/dracclient/client.py
src/pilot/discover_nodes/discover_nodes/dracclient/resources/nic.py

@cdearborn @rpioso @digambar15 
Note:
Closed the previous PR for the same story due to some problem in it. This is a new PR which contains all the changes.

Use upstreamed nic configuration methods and remove downstream counterparts

---

src/pilot/assign_role.py
src/pilot/config_idrac.py
src/pilot/discover_nodes/discover_nodes.py

@cdearborn @rpioso @digambar15 
This PR is an extension of https://github.com/dsp-jetpack/JetPack/pull/202

Removed unnecessary changes from upstreamed system properties

---

src/deploy/osp_deployer/director.py
src/deploy/osp_deployer/settings/config.py
src/pilot/assign_role.py
src/pilot/config_idrac.py
src/pilot/config_idracs.py

Note: A few changes are just for the sake of PEP8
@digambar15 @cdearborn @rpioso

Added ability to skip_baremetal_configuration (NIC and BIOS)

---

src/pilot/constants.patch
src/pilot/dracclient_raid.patch

@cdearborn @digambar15 @dpaterson  Guys, i have fix the issue with is_boss_controller method by properly updating it's return value and added missing class in constant.py file. 
Please review it

Fix for is_boss_controller method and constants file using Monkey Patch

---

src/pilot/config_idrac.py

@cdearborn @rpioso @digambar15  Please review the code.

Fix mac address attribute from mac_address to mac

---

src/deploy/osp_deployer/director.py
src/deploy/osp_deployer/settings/config.py
src/deploy/osp_deployer/settings/sample_csp_profile.ini
src/deploy/osp_deployer/settings/sample_xsp_profile.ini
src/pilot/deploy-overcloud.py
src/pilot/templates/dellemc-unity-cinder-backend.yaml

Added automation support for unity cinder backend

Support for Unity Cinder Backend

---

src/pilot/install-director.sh

This patch adds back in the patch for the original RAID realtime support.

Add back in the original realtime support

---

src/deploy/osp_deployer/director.py
src/deploy/osp_deployer/profiles/csp.json
src/deploy/osp_deployer/profiles/xsp.json
src/deploy/osp_deployer/settings/config.py
src/deploy/osp_deployer/settings/sample_csp_profile.ini
src/deploy/osp_deployer/settings/sample_xsp_profile.ini
src/deploy/osp_deployer/settings_sanity.py
src/pilot/deploy-overcloud.py
src/pilot/install-director.sh
src/pilot/templates/octavia.yaml

Added a flag in settings.ini files to enable/disable Octavia load balancer at deployment time.
Also, provided an option for Users to disable Octavia generated certificates and keys for secure communication between Octavia containers and amphora load balancer and provide their own certificates and keys in settings.ini files.

Octavia support for JS 13.1

---

src/deploy/osp_deployer/settings/config.py
src/deploy/osp_deployer/settings/sample_csp_profile.ini
src/deploy/osp_deployer/settings/sample_xsp_profile.ini

Unity Fixes

---

src/pilot/wsman.patch

Updated number elements requested during an enum or pull to 384 to follow
recommended best practices for performance.

Updated number elements requested during an enum or pull

---

src/deploy/osp_deployer/director.py
src/deploy/osp_deployer/settings/config.py
src/deploy/osp_deployer/settings/sample_csp_profile.ini
src/deploy/osp_deployer/settings/sample_xsp_profile.ini
src/pilot/deploy-overcloud.py
src/pilot/templates/manila-unity-config.yaml

Config support for Unity Manila Backend

Support for Unity Manila Backend

---

src/pilot/config_idrac.py

The introduction of this bug was caused by a bad manual merge made by your's truly.

This patch fixes switching a node from BIOS to UEFI boot

---

src/pilot/install-director.sh

Reverts dsp-jetpack/JetPack#279

Revert " removed deprecated undercloud setting"

---

src/pilot/install-director.sh

Revert "Revert " removed deprecated undercloud setting""

---

src/pilot/discover_nodes/discover_nodes.py

@cdearborn @digambar15 Please review the code. Invoke made using is_idrac_ready() method in discover_nodes module.

iDRAC not ready for discover_nodes

---

src/deploy/osp_deployer/director.py

RH Container Catalog Login access to registry.connect.redhat.com is required. Subscription login should also work

Unity cinder and manila container deployment

---

src/deploy/osp_deployer/settings/sample_csp_profile.ini
src/deploy/osp_deployer/settings/sample_xsp_profile.ini

Added additional notes for tempest_smoke_only flag

---

src/pilot/deploy-overcloud.py

Unity: Added support for Manila Share Types

---

src/pilot/install-director.sh

This merges all the changes to install-director.sh from master into experimental.  This includes the fix for the ceph deployment failing.

Merging fix for failed ceph deployment from master

---

src/pilot/deployment-validation/sanity_test.sh

Instance creation fails with sanity test ( glance backend via cinder
Fixed the scope

Fixed CES-1081 Glance via cinder, breaks sanity

---

src/deploy/osp_deployer/settings/sample_csp_profile.ini
src/deploy/osp_deployer/settings/sample_xsp_profile.ini

There is a need to re-arrange and add verbiage to the JetPack .ini files Backend section
for multiple backends

Arrange and add verbiage to the JetPack .ini files Backend section

---

src/pilot/deployment-validation/sanity_test.sh

Ran it on my stamp and kurt's with various options and tested it

Make sanity test flags case insensitive

---

src/deploy/osp_deployer/director.py

Avoid err. message showing up in logs

handle docker images cleaning 

---

src/deploy/osp_deployer/deployer.py
src/deploy/osp_deployer/director.py
src/deploy/osp_deployer/settings/config.py
src/deploy/osp_deployer/settings/sample_csp_profile.ini
src/deploy/osp_deployer/settings/sample_xsp_profile.ini

Added ability to change tempest workspace by changing the value
of tempest_workspace in the .ini file.
Also did a bit of cleanup and refactoring to improve execution
and readability.

Add tempest_workspace setting and cleanup

---

src/pilot/deployment-validation/sanity_test.sh

1. Create shares in tenant scope aka sanity
2. Use floating network to create shares
3. Allow access to the sanity VM
4. Mount the share to the VM

Manila Share Fixes

---

src/pilot/config_dashboard.py

Cherry-picked from master since also affected 13.0 branch

remove ansible patches from previous release

---

src/deploy/osp_deployer/director.py

This patch adds a missing pool into the Ceph OSD algorithm calculator.

Add missing Ceph pool

---

src/pilot/discover_nodes/discover_nodes.py

Hi @cdearborn , This PR is regarding fix in discover_nodes.py file. as it was still showing dracclient import from discover_nodes.

FIX dracclient import in discover_nodes.py file

---

src/pilot/raid.patch

Hi @cdearborn ,
This is the recent monkey patch for my upstream patch [664633](https://review.opendev.org/#/c/664633/).
I have tested patch manually and it successfully applies the patch.
However i have not test against full deployment. I will update this PR once full deployment is completed.
Please dont merge untill then.
Thanks.

Monkey patch for delete_configuration patch enhancements

---

src/pilot/dracclient_raid.patch

This patch fixes an error that occurs when applying the dracclient raid patch.

WIP: Fixed dracclient_raid.patch

---

src/deploy/osp_deployer/director.py
src/deploy/osp_deployer/settings/config.py
src/deploy/osp_deployer/settings/sample_csp_profile.ini
src/deploy/osp_deployer/settings/sample_xsp_profile.ini
src/pilot/deploy-overcloud.py
src/pilot/templates/dell-cinder-backends.yaml
src/pilot/templates/dellsc-cinder-config.yaml

Use the environment files(heat templates)
instead of extra config ( puppet directly)
This will help with upgrades

DellSc Config deployment refactoring

---

src/pilot/config_idrac.py
src/pilot/discover_nodes/discover_nodes.py

@cdearborn @digambar15 
I have removed code from config_idrac.py and moved it to discover_node.py.
And I have also tested recovery_mode code changes in discover_node by running full deployment .
Instack.json is created properly and also able to take node out of recovery.

moved recovery code from config_idrac to discover_node

---

src/pilot/dell_systems.json

 updated default pxe nic's 

---

src/pilot/raid.patch

Hi Chris,
I have added fix for job creation for multiple controllers  which merged recently: 
[680660](https://review.opendev.org/#/c/680660/)
I have tested patch manually without any issue. 
-Rachit

monkey_patch Fix for job_creation with multi controllers

---

src/pilot/inspect.patch

Hi Chris,
During deployment i just found that pxe nic support changes are reflected in ironic upstream inspect.py installed by osp_13 on director. Also this patch is been tested and its working successfully.
Rachit

pxe nic support landed in osp_13 release

---

src/mgmt/osp-sah.ks

The messages on ssh have been removed. And bridging problem has been resolved. Only the bridge with public IP address should have the Gateway IP.

Resolved sah network for rhel8.1, removed ssh banners

---

src/pilot/customize_image.sh

This is a temporary fix for the HBA330 issue which will fix the issue on R73.

Workaround for HBA330 issue

---

src/pilot/client.patch
src/pilot/dracclient_raid.patch
src/pilot/job.patch
src/pilot/wsman.patch

This patch updates the patches for the OSP13z9 release.

Updated patches for z9

---

src/pilot/customize_image.sh

Patch is implemented using the virt-customize command. To validate the patch 
- ssh storage node
- goto /etc/default/grub
- mpt3sas.prot_mask=1 parameter will be present against the value GRUB_CMDLINE_LINUX

T10 PI format patch

---

src/deploy/osp_deployer/director.py

allow for non "osp_admin" users in undercloud.conf

xtra undercloud.conf settings

---

src/deploy/osp_deployer/checkpoints.py
src/mgmt/deploy-director-vm.sh
src/pilot/containers-prepare-parameter.yaml
src/pilot/customize_image.sh
src/pilot/install-director.sh

1- Updated some python3 and podman related code
2- Updated repos and some minor things in undercloud installation code
3- Fixed the error at virt-customize commands
4- Commented out patches for deprecated files and locations
5- Updated installation success checks and logs

fixes for rhosp16 undercloud deployment and virt-customize

---

src/common/thread_helper.py
src/deploy/osp_deployer/deployer.py
src/pilot/config_idrac.py
src/pilot/config_idracs.py
src/pilot/install-director.sh

adding ironic python dependencies to undercloud host
python3 edits

CES-10988 

---

src/pilot/dracclient_raid.patch

Hi Chris, 
I have added a change for which if RAIDStatus is not found then it will take RaidStatus.
Thanks, 
Rachit

Added : RaidStatus with RAIDStatus attribute

---

src/deploy/osp_deployer/director.py
src/pilot/config_dashboard.py
src/pilot/credential_helper.py
src/pilot/deploy-overcloud.py
src/pilot/identify_nodes.py
src/pilot/nfv_parameters.py
src/pilot/register_overcloud.py

Osp16 miscs

---

src/pilot/dracclient_raid.patch

This is a temporary patch to make JetStream work with LCC 4.00.00.00

Update: use RaidStatus if RAIDStatus node found

---

src/pilot/config_idrac.py

config_idrac.py:config_idrac has wrong model_properties default argument. Parsing through utils.py to parse JSON.

CES-10736 bug fix

---

src/pilot/undercloud.conf

Hardcoded 'osp_admin' user in undercloud.conf changed to generic user

CES-11054 bug fix

---

src/pilot/assign_role.py

Cherry picking the power state sys021 fix into the experimental ironic branch.

SYS021 (#506)

---

src/pilot/install-director.sh
src/pilot/power.patch
src/pilot/raid.patch

Hi Chris,
I have added a monkey patch for latest drives conversion code including the two bug fix which recently raised.
Below are the patches :
- DRAC: Drives conversion from RAID to JBOD:  https://review.opendev.org/671038
- DRAC: Drives conversion from JBOD to RAID: https://review.opendev.org/679093
Bug fixes:
- DRAC: Fix a failure to create virtual disk bug: https://review.opendev.org/710852 (upstream patch not merged)
- DRAC: Fix RAID create_config clean step: https://review.opendev.org/707169 (Merged)
Rachit

Updated latest code: drives conversion and create VD

---

src/pilot/deploy-overcloud.py

https://jira.gtie.dell.com/browse/CES-11151

Fixing manila share creation error

---

src/pilot/install-director.sh
src/pilot/power.patch
src/pilot/raid.patch

Fixes for RAID/JBOD drive conversion and the SYS021 reboot error.

Ironic fixes

---

src/pilot/containers-prepare-parameter.yaml
src/pilot/deploy-overcloud.py
src/pilot/templates/network-isolation.yaml
src/pilot/templates/nic-configs/5_port/controller.yaml
src/pilot/templates/nic-configs/5_port/dellcompute.yaml
src/pilot/templates/nic-configs/5_port/storage.yaml
src/pilot/templates/roles_data.yaml

Minor Z2/template updates

---

src/deploy/osp_deployer/profile.py
src/deploy/osp_deployer/sah.py
src/deploy/osp_deployer/settings_sanity.py

Refactored to get setup_usb_idrac.py working with RHEL8/Python 3.8
Fixes: CES-11199

Refactored to get setup_usb_idrac.py working with RHEL8/Python 3.8

---

src/pilot/raid.patch

Hello Chris,
This change is regarding the ironic upstream patch[730725](https://review.opendev.org/#/c/730725) which add support for RAID controller to convert  to RAID mode from EHBA mode.
Ironic patch is currently not merged. But changes are approved.
Thanks,
Rachit

Monkey patch for ehba support in ironic

---

src/deploy/osp_deployer/director.py
src/deploy/osp_deployer/settings/sample_xsp_profile.ini

Missed a cpl of *2 attributes for second edge network example

Update sample ini with new edge subnet attr

---

src/pilot/templates/nic-configs/4_port_hci/controller.yaml
src/pilot/templates/nic-configs/4_port_hci/dellcomputehci.yaml
src/pilot/templates/nic-configs/4_port_hci/nic_environment.yaml
src/pilot/templates/nic-configs/5_port_hci/controller.yaml
src/pilot/templates/nic-configs/5_port_hci/dellcomputehci.yaml
src/pilot/templates/nic-configs/5_port_hci/nic_environment.yaml

- 4_port_hci & 5_port_hci templates. version => rocky

HCI Network Templates

---

src/deploy/osp_deployer/director.py
src/deploy/osp_deployer/profiles/csp.json
src/deploy/osp_deployer/profiles/xsp.json
src/deploy/osp_deployer/settings/config.py
src/deploy/osp_deployer/settings/sample_csp_profile.ini
src/deploy/osp_deployer/settings/sample_xsp_profile.ini
src/pilot/deploy-overcloud.py
src/pilot/templates/dellemc-powermax-fc-cinder-backend.yaml
src/pilot/templates/dellemc-powermax-iscsi-cinder-backend.yaml
src/pilot/templates/powermax-manila-config.yaml

Backport PowerMax and Unity into JS-16.1/OSP16 branch

Backport PowerMax and Unity into JS-16.1/OSP16 branch

---

src/deploy/osp_deployer/settings/sample_hci.properties
src/deploy/osp_deployer/settings/sample_hci_profile.ini
src/pilot/templates/first-boot.yaml
src/pilot/templates/nic-configs/4_port_hci/dellcomputehci.yaml
src/pilot/templates/nic-configs/5_port_hci/dellcomputehci.yaml

HCI support fixes/updates

---

src/deploy/osp_deployer/profiles/csp.json
src/deploy/osp_deployer/profiles/xsp.json
src/deploy/osp_deployer/settings/config.py
src/deploy/osp_deployer/settings/sample_csp_profile.ini
src/deploy/osp_deployer/settings/sample_xsp_profile.ini

The first draft of ini file settings for VxFlexOS. Have deployed and tested it.

PowerFlex  Settings support

---

src/pilot/install-director.sh
src/pilot/nova-scheduler-container.patch
src/pilot/redis-container.patch
src/pilot/swift-proxy-container.patch

added patches to fix an issue with nova scheduler preventing instances creation (bz 1846020)

CES-11250 part II

---

src/deploy/osp_deployer/settings/sample_csp_profile.ini
src/deploy/osp_deployer/settings/sample_hci_profile.ini
src/deploy/osp_deployer/settings/sample_xsp_profile.ini
src/pilot/nfv_parameters.py
src/pilot/templates/dell-environment.yaml

- Updated NUMA-CPUs code
- Added some missing parameters in sample ini files

Numa code updated, added missing parameters to sample ini files

---

src/pilot/templates/dell-environment.yaml
src/pilot/templates/neutron-ovs-dpdk.yaml
src/pilot/templates/neutron-sriov.yaml
src/pilot/templates/ovs-hw-offload.yaml

- Some outdated filters (e.g RamFilter) are removed
- Some additional filters added for ovs-hw-offload

Updated NFV nova scheduler filters

---

src/pilot/dell_nfv.py
src/pilot/deploy-overcloud.py
src/pilot/nfv_parameters.py
src/pilot/templates/dell-environment.yaml
src/pilot/templates/neutron-ovs-dpdk.yaml

- Updated the deprecated parameters for numa
- Fixed CPU cores calculations for NUMA and OVS-DPDK
- Log details for cpu and nics on numa nodes

Vlan networks fix, Isol Cpu Fix for numa and DPDK

---

src/deploy/osp_deployer/director.py
src/pilot/templates/neutron-sriov.yaml
src/pilot/templates/nic-configs/sriov_6_port/controller.yaml
src/pilot/templates/nic-configs/sriov_6_port/dellcompute_sriov.yaml
src/pilot/templates/nic-configs/sriov_6_port/storage.yaml
src/pilot/templates/nic-configs/sriov_7_port/controller.yaml
src/pilot/templates/nic-configs/sriov_7_port/dellcompute_sriov.yaml
src/pilot/templates/nic-configs/sriov_7_port/storage.yaml
src/pilot/templates/nic-configs/sriov_8_port/controller.yaml
src/pilot/templates/nic-configs/sriov_8_port/dellcompute_sriov.yaml
src/pilot/templates/nic-configs/sriov_8_port/storage.yaml
src/pilot/templates/nic-configs/sriov_9_port/controller.yaml
src/pilot/templates/nic-configs/sriov_9_port/dellcompute_sriov.yaml
src/pilot/templates/nic-configs/sriov_9_port/storage.yaml
src/pilot/templates/roles_data.yaml

- Added new sriov templates for 16.1
- Replaced SRIOV Deprecated paths and parameters
- Update code for editing templates

SRIOV deployment support, templates

---

src/deploy/osp_deployer/director.py
src/deploy/osp_deployer/settings/config.py
src/deploy/osp_deployer/settings/sample_csp_profile.ini
src/deploy/osp_deployer/settings/sample_hci_profile.ini
src/deploy/osp_deployer/settings/sample_xsp_profile.ini
src/pilot/customize_image.sh
src/pilot/install-director.sh

removing references to ceph pool & cleaning up related scripts

CES-11554  

---

src/pilot/deploy-overcloud.py

Forgot to include the re-ordering of dvr-template in the previous PR for DVR . This will override ovs parameters to deploy DVR.

DVR template re-order

---

src/deploy/osp_deployer/director.py
src/deploy/osp_deployer/settings/config.py
src/deploy/osp_deployer/settings/sample_csp_profile.ini
src/deploy/osp_deployer/settings/sample_hci_profile.ini
src/deploy/osp_deployer/settings/sample_xsp_profile.ini
src/pilot/deployment-validation/sanity.ini
src/pilot/deployment-validation/sanity_test.sh

The support for sanity test for manila shares was not migrated
from JS13.3

Fixing CES-11633 Sanity does not support for Unity in JS-16.1 release

---

src/pilot/assign_role.py

Added code for getting sas_address attribute when RAID-0 VD's are configured.

CES-11660 : Fix for sas_address issue

---

src/pilot/nfv_parameters.py

Added NUMA support for R7515s.
To test this and any of the other NFV features on AMD servers, make sure Cpu Socket is in NPS2 mode (2 Numa Partitions) in bios.

NUMA Support for AMD

---

data/vlock_files/containers-prepare-parameter.yaml
src/deploy/jinja2_templates/nic-configs/compute_edge.j2.yaml
src/deploy/osp_deployer/settings/sample_csp_profile.ini
src/deploy/osp_deployer/settings/sample_hci.ini
src/deploy/osp_deployer/settings/sample_powerflex.ini
src/deploy/osp_deployer/settings/sample_xsp_profile.ini
src/pilot/deployment-validation/sanity.ini

Merging missing commits from latest release in master.

Js 16.1.21 2 missing commits 

---

src/deploy/osp_deployer/director.py
src/pilot/nfv_parameters.py
src/pilot/undercloud_hieradata.yaml

This PR contains fixes for,
- Overcloud deployment failure issue that we were facing on **15G**
- Modified formula for Ceph pgs calculation
- Small fix for NFV
@gaelrehault kindly review it and let me know if you have any concerns? Thanks

Fixes for Ceph pgs, Ironic & NFV

---

src/pilot/dracclient_raid.patch
src/pilot/install-director.sh

CES-12484 Patch support for H755 RAID controller
