dsp-jetpack/JetPack

src/pilot/introspect_node.py, src/pilot/introspect_nodes.py, src/pilot/ironic_helper.py
This patch changes the introspection logic so that it waits for OOB
introspection to complete before attempting to change the node state to
available.
=> CES-9172: introspection fails due to locked node

src/pilot/dracclient_raid.patch, src/pilot/install-director.sh, src/pilot/uris.patch
This patch adds support for NVMe drives to python-dracclient. A patch has been submitted upstream for this work, so we will need to remove this downstream patch eventually.
See: https://review.openstack.org/#/c/542911/
=> Patch support for NVMe drives into python-dracclient

src/pilot/templates/nic-configs/4_port/compute.yaml, src/pilot/templates/nic-configs/4_port/controller.yaml, src/pilot/templates/nic-configs/4_port/nic_environment.yaml, src/pilot/templates/nic-configs/4_port/storage.yaml, src/pilot/templates/nic-configs/5_port/compute.yaml, src/pilot/templates/nic-configs/5_port/controller.yaml, src/pilot/templates/nic-configs/5_port/nic_environment.yaml, src/pilot/templates/nic-configs/5_port/storage.yaml
The bonding mode requires "mode=802.3ad" instead of just "802.3ad".
=> Fixed mistake in bonding options

src/pilot/assign_role.py
1. List all the controllers and find boss controller from it
2. Find out the boss card from physical disks using controller model id
4. Calculate the boss card size in GB
5. Pass to select_os_volume method.
6. When we pass the voume size to that method, method directly submit to ironic client
=> Detecting boss card and select os volume

src/pilot/deploy-overcloud.py
This is to get rid out the urllib3 warning we have since i changed all print statement to logger statement.
See below.
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.120.9
=> Configuring logger to pull out urllib3 warnings

src/pilot/deploy-overcloud.py
This fixes:
- deploy-overcloud.py errors out due to bad configure_logging call
- urlib3 floods the log with logging messages
=> Fix logging in deploy-overcloud.py

src/deploy/osp_deployer/director.py
Currently use_custom_instack doesn't work because the instackenv.json is
copied to the director node as root.  config_idrac then tries to edit the
file and that fails because the director user does not own the file.
This is a temporary fix to change ownership of the file to the director user.
=> Temporary fix to make use_custom_instack work

src/pilot/install-director.sh, src/pilot/wsman.patch
This patch fixes an issue where on some stamps, when enumerating
DCIM_ControllerView, the iDRAC can return invalid unprintable
characters in the DriverVersion field.
This patch catches an XMLSyntaxError generated by etree.fromstring() during
enumeration and when it occurs, it strips out the unprintable characters and
reparses the XML in addition to logging the offending XML and the exception.
=> Fix deployment failure due to invalid characters from iDRAC

data/vlock_files/director_vm.vlock
This patch updates the director VM vlock file to resolved issues that have
resulted of RHEL 7.5 shipping.
=> Updated director VM vlock file

src/deploy/osp_deployer/profiles/csp.json
This fix allows the user to set dpdk to disable even if he's using a csp profile. It reduces enforcement but allows flexibility. Hopefully solving the bug Kurt went through.
=> Changing dpdk_enable enforcement for CSP Profile

src/deploy/osp_deployer/settings/sample.properties
With the BOSS card enhancements, os_volume_size_gb is no longer needed in the .properties file.
=> Removed os_volume_size_gb from storage nodes

src/deploy/osp_deployer/settings/sample_csp_profile.ini, src/deploy/osp_deployer/settings/sample_xsp_profile.ini
Replaced "&" with "and" so copying and pasting these files into the docs sample files does not cause a docs explosion.
=> Replaced "&" with "and" so copying and pasting into docs works

src/deploy/osp_deployer/profiles/csp.json, src/deploy/osp_deployer/profiles/xsp.json, src/deploy/osp_deployer/settings/sample_csp_profile.ini, src/deploy/osp_deployer/settings/sample_xsp_profile.ini
- Added min value for mariadb_max_connection to 151 which is default in mariadb
- Changes min value for innodb_buffer_pool_instances to 8 which is also default
=> Change min value for maraidb_max_connection and innodb_buffer_pool_instances

src/pilot/templates/roles_data.yaml
This patch comments out inclusion of the ManilaBackendGeneric service
as this service was removed in the latest OSP10 bits.
=> Deployment fails with ManilaBackendGeneric error

src/pilot/assign_role.py, src/pilot/dell_systems.json
- This patch adds support for the DSS9000 by adding a NIC entry to
dell_systems.json.
- It also adds support for storage nodes that only have an HBA330 and no BOSS
card since this is the way that the DSS9000 storage nodes were configured.
=> Add support for DSS9000

src/pilot/ironic.patch
This patch bumps up the cleaning steps timeout to 45 minutes from the default
of 30 minutes.  This allows enough time for RAID creation to complete before
the cleaning timeout occurs.
=> Fix for CES-9949: DRAC 500 errors

src/pilot/assign_role.py
The DSS9k nodes did not have BOSS cards, only HBA330s.  This change makes it so that only an HBA330 needs to be present for assign_role to auto generate the Ceph OSD configuration.
=> Only require HBA330 to be present for auto OSD config generation

src/pilot/constants.patch, src/pilot/install-director.sh
Increased iDRAC is-ready retries to 96, which is required for the latest firmware.
=> Increased iDRAC is-ready retries to 96

src/pilot/wsgi.patch
The upstream fix for the http 500 issue is 4 processes * 15 threads, for a total of 60 threads.
This PR changes the patch to match that, which addresses 500 errors on 13G stamps.
=> Changed threads to match upstream fix

src/pilot/ironic.patch
This patch increases node locked retries, which addresses the node locked errors that were popping up with the new firmware.
=> Increased node locked retries to address node locked errors

boot_mode_helper.py, src/pilot/boot_mode_helper.py
Below tasks are implemented -
1.  Determine current boot mode
2.  Check is_boot_order_flexibly_programmable() method
3. Define dictionary to change the boot order from drac to ironic and vice-versa
=> CES-9801 - Helper functions to determine boot mode, BIOS or UEFI

src/pilot/customize_image.sh
.. for BZ 1472409
Ceph is now containerized / that file is gone from latest overcloud image coming in next ZStream
=> removing ceph workaround

src/pilot/assign_role.py
This adds back in the code that checks to see if the generated OSD config is
different from the current OSD config.  This prevents erroneous failures when
redeploying just the overcloud.
=> Fix for CES-10049: Deployment fails with OSD configuration error

src/pilot/config_idrac.py
Set 'boot_mode' in 'capabilities' parameter within 'properties' field of ironic node to 'bios' or 'uefi'.
=> CES-9805 - Set boot_mode in ironic node's capabilities

src/deploy/osp_deployer/profiles/csp.json, src/deploy/osp_deployer/profiles/xsp.json, src/deploy/osp_deployer/settings/sample_csp_profile.ini, src/deploy/osp_deployer/settings/sample_xsp_profile.ini
- Fixed names of sriov network environment files from "sriov_7_ports"/"sriov_9_ports" to "sriov_7_port"/"sriov_9_port" to follow the same naming pattern.
- Fixed typo in the comment.
- changed default value of "sriov_vf_count" parameter.
=> SR-IOV changes 

src/pilot/assign_role.py
This fixes the issue where the osds defined in templates/ceph-osd-config.yaml were ignored.
=> fix for nodes uuids case to match up 

src/pilot/assign_role.py
- Removed is_jbod_capable method from assign_role.py.
- Used is_jbod_capable method from upstream in assign_role.py.
@cdearborn @digambar15
=> Use upstreamed is_jbod_capable CES-10113

src/deploy/osp_deployer/settings/sample_csp_profile.ini
Evidently NUMA and hugepages require IB introspection, so enforce IB introspection for the CSP profile.
=> Enforce IB introspection for CSP profile

src/pilot/install-director.sh
Temporarily commenting out the RAID patch since it patches realtime changes into ironic, but no corresponding changes are being patched in to python-dracclient.
=> Fixing RAID configuration

src/pilot/config_idrac.py
The issue is that the PxeDev1EnDis attribute is randomly set to disabled.
This causes the PxeDev1Interface attribute to be read-only, which in
turn causes python-dracclient to throw an exception because we're trying
to set a read-only attribute.
Note that this happens only sometimes on the latest firmware.
The fix changes config_idracs as follows:
1. Set the boot mode in a job and commit it.
This will cause an extra reboot for BIOS boot mode.
2. When the boot mode is UEFI, set PxeDev1EnDis in a job and commit it.
This causes an extra reboot for UEFI boot mode.
3. After PxeDev1EnDis has been set, set PxeDev1Interface
This change will be bundled in with the reboot for all the other jobs.
=> This patch fixes an intermittent issue when configuring the UEFI PXE NIC

src/pilot/ironic.patch
This patch doubles the RAID cleaning timeout as it was not long enough for
some servers.
=> Fix for RAID cleaning timeout failure

src/deploy/osp_deployer/director.py, src/deploy/osp_deployer/profiles/csp.json, src/deploy/osp_deployer/profiles/xsp.json, src/deploy/osp_deployer/settings/config.py, src/deploy/osp_deployer/settings/sample_csp_profile.ini, src/deploy/osp_deployer/settings/sample_xsp_profile.ini, src/pilot/templates/dell-environment.yaml
Define the backend to use for Glance in the ini file.
For cinder
glance_backend=cinder
Set to rbd to use ceph as backend.
glance_backend=rbd
Set to file to use file-based storage for images.
glance_backend=file
And deploy overcloud
Note: cinder has to be configured to use the right backend
if cinder is choosen
=> Add support for Glance Backend Option

src/pilot/deployment-validation/sanity_test.sh, src/pilot/nfv_parameters.py
Sanity was trying to ping the VM before it was active. Adding the delay of 20 gives the instance time to be active before sanity test can ping it.
=> Fix for CES-10376: Sanity test is failing to ping vlan-aware VM

src/pilot/install-director.sh, src/pilot/wsman.patch
This patch fixes python-dracclient so that it filters out all
non-printable characters during an enumeration instead of just
non-ASCII characters.
=> Fix for CES-10391: list_controllers fails due to ASCII 3

src/pilot/client.patch
The current code waits for 3 consecutive failed pings, each 10 seconds
apart to determine that an iDRAC has gone down during an iDRAC reset.
This is too long for some servers, as the iDRAC may come back up before
the 3rd ping failure. This results in a failure to detect the iDRAC
going down, which causes a timeout on the reset. This patch changes the
code to wait for only 2 consecutive ping failures, which is what our
highly tested downstream code does.
=> Fix iDRAC reset

src/pilot/assign_role.py
The OSD configs need to be indexed by the UUID of the server, not the ID.
=> Fixes OSD config generation

src/pilot/prep_overcloud_nodes.py
This patch make the prep script correctly set the overcloud nodes to pxe boot permanently.
The prior code made the overcloud nodes PXE boot one time only.
=> Set overcloud nodes to pxe boot permanently

src/deploy/osp_deployer/director.py, src/deploy/osp_deployer/infra_host.py, src/deploy/osp_deployer/settings/config.py, src/pilot/templates/dell-environment.yaml
This patch changes the ceph configuration so that instead of reducing the replication count to fit hardcoded pg_nums and the number of OSDs in the cluster, it counts up the number of OSDs in the cluster, leaves the replication factor set to 3, and calculates what the pg_nums should be for each pool.  It then updates the dell-environment.yaml with these numbers.
=> Autocalculate pg_nums

src/pilot/deploy-overcloud.py
Simplied cinder type creation. Previously we had equallogic which supported
multiple instances. We don't have that complexity anymore
=> Storage changes for cinder type creation

src/deploy/osp_deployer/deployer.py, src/deploy/osp_deployer/director.py
If sanity test is not run prior to attempting to
configure tempest an excption would occur when the
tempest configuration script was called. This patch
insures that the network the config script requires
is present, if it is not then the user is instructed
to run the sanity test to create the network and
to rerun the deployment with the --tempest_config_only
flag.
Added new mutually exclusive arguments:
--tempest_config_only - helps the user
recover from error where tempest.conf could not be
generated due to the sanity test failing or not
running at all, as executing it is currently an
option. If tempest.conf already exists it is backed
up and a new one created.
--run_tempest_only - Just run Tempest. If no tempest.conf
is found we try to generate one then run.
Lastly, added new mutually …
=> Handle tempest config if public network not avail

src/deploy/osp_deployer/deployer.py, src/deploy/osp_deployer/settings/sample_csp_profile.ini, src/deploy/osp_deployer/settings/sample_xsp_profile.ini
Arg should have been validate_only not validate_settings_only,
there were two different versions in original and merged wrong
one.
=> Touch up tempest comments, arg to validate_only

src/deploy/osp_deployer/deployer.py, src/deploy/osp_deployer/director.py
When doing a full deployment instead of outputting an exception
when sanity test has NOT been run, add a check to see if the
subnet sanity test should have created exists prior to trying
to configure tempest.
=> Refactor tempest config

src/pilot/install-director.sh, src/pilot/templates/ceph-osd-config.yaml
This fixes an issue introduced upstream we picked with the latest ZStream, causing the overcloud deployment to fail 
Root cause is the following commit : 
https://github.com/openstack/tripleo-heat-templates/commit/759b711b9457a5827cf75e8dcb36e3ca905dec1c#diff-801e6ddf38ed5e45c3f6038fefdaf4c6
=> workaround for tripleo-heat-templates 

src/deploy/osp_deployer/director.py, src/deploy/osp_deployer/settings/config.py, src/deploy/osp_deployer/settings/sample_csp_profile.ini, src/deploy/osp_deployer/settings/sample_xsp_profile.ini
Adding support to pull a specific version of the custom container for unity. The default is 'latest'. This helps to lock the version if the latest image is bad or not deployable.
=> Unity: Support specific version of container image

src/deploy/osp_deployer/settings/sample_csp_profile.ini, src/deploy/osp_deployer/settings/sample_xsp_profile.ini
This patch bumps up the default deployment timeout to 180 minutes.
=> Bump up deployment timeout

src/deploy/osp_deployer/director.py, src/pilot/templates/dell-environment.yaml
When enable_rbd_backend is set to false should not install ceph as cinder backend.
But JS is still installing ceph as cinder backend
Fixed it
=> Disable ceph cinder backend when the flag is set

src/pilot/inspect.patch, src/pilot/install-director.sh
Setting the boot_mode has not yet made it into OSP.  This patch adds it back in.
=> Add back in setting boot_mode

src/pilot/assign_role.py, src/pilot/client.patch, src/pilot/dracclient_raid.patch
This change patches in the changes to python-dracclient to make is_raid_controller return True for BOSS cards.  It also makes the necessary
changes to assign_role to use this change.
=> Fix is_raid_controller

src/pilot/assign_role.py
Fix RAID/JBOD conversion to only create a config job if a commit is needed.
=> Fix RAID/JBOD conversion to only commit if needed

src/pilot/assign_role.py
The patch temporarily disables RAID/JBOD conversion since it appears to not
work on some servers.
=> Disable realtime RAID/JBOD conversion

src/deploy/osp_deployer/director.py, src/pilot/templates/dell-environment.yaml
This patch adds in specifying all of the Ceph OSD pool sizes, which prevents
unspecified pools from defaulting to 128 PGs.  This prevents the number of
PGs from exceeding the total available when you have a low OSD count.
=> Fix deploy with low OSD count

src/pilot/client.patch, src/pilot/dracclient_raid.patch
Created monkey patch of reset_raid_config, clear_foreign_config (RAID deletion enhancement) and is_ready best practice (Checking LCStatus instead of MessageID) for dracclient  client.py and raid.py .
=> Monkey patch for reset_raid_config,clear_foreign_config and is_idrac_ready best practice

src/pilot/client.patch, src/pilot/config_idrac.py, src/pilot/job.patch, src/pilot/lifecycle_controller.patch, src/pilot/utils.patch
@cdearborn @rpioso @digambar15 
modified config_idrac.py in JetStream calling directly into python-dracclient to check if a node is in recovery mode and take it out of recovery mode if necessary.
And also created monkey patch for client.py, job.py, utils.py and lifecycle_controller.py
=> Take lifecycle controller out of recovery mode

src/pilot/inspect.patch
This patch monkey patches in the fix for setting pxe_enabled on ironic ports
during OOB introspection.
=> Fix PXE booting issues during deployment

src/pilot/install-director.sh
Hi @cdearborn ,
This PR includes addition of utils monkey patch in install-director.sh script.
As this patch call was missing in install-director.sh script.
=> adding utils monkey patch call in install_director.sh

src/pilot/assign_role.py
This patch is a Fix to perform drives conversion from RAID to JBOD and vice versa in realtime.(PS : [CES-6956](https://jira.dellemc-community.org/browse/CES-6956) 
Due to current firmware issue, ironic is not able  to create configuration job in realtime.
For more details, i have raised a bug (PS: [CES-10788](https://jira.dellemc-community.org/browse/CES-10788).
=> create logical disks with physical disks w.r.t free_size_mb

src/pilot/assign_role.py
Hi @cdearborn ,
I have completed deployment on 13G(R145) till assign_role(and it executing further to `Installing the overcloud`) with latest pull successfully by removing variable which disables realtime drives conversion.
Please take a look.
Thanks
=> Enabled realtime support for drives conversion in JBOD/RAID

src/pilot/raid.patch
Hi @cdearborn ,
I have added monkey patch fix for upstream patches :
-  RAID creation with multiple controllers [674765](https://review.opendev.org/#/c/674765/)
-  create job in commit_to_controllers when only ``is_commit_required`` is ``True`` [682376](https://review.opendev.org/682376) 
All above change is related to one file raid.patch in upstream ironic
Please take a look.
=> Fix for raid creation on multi controllers and job creation

src/mgmt/osp-sah.ks
Replaced python 2.7 with python 3.6
Firewall service is included by default in rhel8 and disabled in kickstart
List of Packages to be installed is updated accordingly
NTP configurations are replaced by chrony configurations
=> Kickstart Changes for RHEL8

src/pilot/install-director.sh, src/pilot/management.patch
Hi Chris,
I have added monkey patch for reset_idrac, known_good_state and clear_job_queue clean steps of management interface.
Please find link of patches below:
1)DRAC: Adding reset_idrac and known_good_state cleaning steps
https://review.opendev.org/#/c/658271/
2)DRAC : clear_job_queue clean step to fix pending bios config jobs
https://review.opendev.org/#/c/674021/
3)DRAC: Fix a bug for clear_job_queue clean step with non-BIOS pending job
https://review.opendev.org/#/c/683161/
Thanks.
=> adding monkey patch for cleaning steps of management interface

src/pilot/drac.patch, src/pilot/install-director.sh, src/pilot/ironic_job.patch, src/pilot/raid.patch
Hi Chris,
I have added monkey patch for drives conversion from jbod to raid-
[679093](https://review.opendev.org/#/c/679093/)
I have tested ironic_job.patch with full deployment  and its working. but i have tested raid.patch manually by running patch command and it works fine.
Thanks
=> Drives conversion jbod to raid prior create_configuration

src/deploy/osp_deployer/settings/sample.properties, src/deploy/osp_deployer/settings/sample_csp_profile.ini, src/deploy/osp_deployer/settings/sample_xsp_profile.ini, src/mgmt/osp-sah.ks
Network configurations are now performed through Kickstart's "network" commands
Configurations have been moved to %pre section where they get included in ks_include.txt
Updated chrony configurations.
In %post section, a work around is included for following issues:
Vlans not being enslaved by bridges in %pre section
STP=yes
ONBOOT=no for prov and pub-api vlans
=> Included SAH-Network Configurations through Kickstart's Network Commands

src/deploy/osp_deployer/settings/sample_csp_profile.ini, src/deploy/osp_deployer/settings/sample_xsp_profile.ini, src/mgmt/osp-sah.ks
KickStart has been updated and following issues have been resolved:
1- Default GW in /etc/sysconfig/network has been removed as it doesn't work and caused conflict with GW in ifcfg files, GW is defined in ifcfg files instead.
2- Excess ntp servers have been removed from example ini files and only one pool is left as example, another pool exists already in chrony.conf by default
3- Removed "firewall --disable"  as it is not required to disable it and current configurations work good regardless of it being enabled or disabled.
4- pip commands have been updated to pip3 for python3.6 compatibility
=> KickStart updates for SAH

src/deploy/auto_common/ipmi.py, src/pilot/identify_nodes.py, src/pilot/register_overcloud.py
Python 3 compile was failing because of redundant braces and due to using a single \ for defining paths.
=> Pyhton 3 compile error fix

src/pilot/assign_role.py
Following features will be implemented as part of this PR -
1. PERC H740P is supported and able to create OSD's successfully.
2. No more need to add osd_disks in .properties file as ceph_osd_config.yaml is generating as expected and Ceph is also picking up all the devices successfully as part of OSD creation.
3. Two controllers (BOSS + PERC) are supported in 14G Storage nodes.
Note - Current testing is done only against PERC H740P controller. Soon we will perform testing both the controllers.
=> Support for BOSS+PERC in 14G storage nodes

src/pilot/customize_image.sh
Patch is implemented using the virt-customize command. To validate the patch
- ssh storage node
- goto /etc/default/grub
- mpt3sas.prot_mask=1 parameter will be present against the value GRUB_CMDLINE_LINUX
=> T10 PI format patch

src/deploy/auto_common/file_utils.py, src/deploy/osp_deployer/checkpoints.py, src/deploy/osp_deployer/director.py, src/deploy/osp_deployer/sah.py, src/mgmt/deploy-director-vm.sh, src/mgmt/director.cfg, src/mgmt/osp-sah.ks, src/pilot/containers-prepare-parameter.yaml, src/pilot/install-director.sh, src/pilot/undercloud.conf
Changes for deploying rhosp 15 undercloud have been included
1- A new undercloud.conf has been included
2- An additional file "src/pilot/containers-prepare-parameter.yaml" is needed while downloading container images. Include your "username: password" in this file before deployment. This feature will be automated in next PR
3- Chrony.conf is configured on SAH node with additional parameters to act like a local NTP server for overcloud and director
=> Deploy OSP15 undercloud

src/pilot/assign_role.py, src/pilot/raid.patch
Hi Chris,
In this PR, i have removed drives conversion(in raid before creating raid config) from ironic in (raid.patch file) as we already discussed that we should not remove drives conversion from Jetpack and osp release should itself put that drives conversion.
Also i have disable again drives conversion in realtime mode as some servers does not let drives convert in either mode in realtime.
Thanks,
-Rachit
=> Disabled realtime drives conversion from jetpack and removed drives conversion in raid from Ironic

src/pilot/config_idrac.py
This patch does the stupid thing and bumps up the time to wait after an iDRAC becomes pingable after a reset to 60 seconds from 30 seconds.  A better fix will be implemented.
=> Increase timeout to wait for iDRAC reboot to finish after reset

src/pilot/dell_systems.json
The pxe_nic slot has changed since we acquired the OCP cards for the XE2420 (Nights Watch).
=> Nights watch model PXE NIC update

src/pilot/assign_role.py, src/pilot/raid.patch
Hi Chris,
As we discuss over call, i have added drives conversion monkey patch for the two upstream ironic patches below.
- DRAC: Drives conversion from raid to jbod: 
- https://review.opendev.org/#/c/671038/
- DRAC: Drives conversion from JBOD to RAID
-  https://review.opendev.org/#/c/679093/
I will remove this monkey patch once osp add this changes to ironic.
Rachit
=> moved drives conversion from jetpack to ironic

src/deploy/osp_deployer/director.py, src/deploy/osp_deployer/settings/sample_csp_profile.ini, src/deploy/osp_deployer/settings/sample_xsp_profile.ini, src/mgmt/deploy-director-vm.sh, src/pilot/containers-prepare-parameter.yaml, src/pilot/deploy-overcloud.py
Includes:
1. OSP 16 rpms updated
2. Added instructions on pulling OVN/OVS based neutron-container
3. overcloud_images.yaml is deprecated, replaced by containers-prepare-parameter.yaml
=> RHOSP16 repo update, overcloud deploy command update

src/pilot/dracclient_raid.patch
Hi Chris,
This is a monkey patch for the recent nvme drives support added to upstream python dracclient. 
Here is the link for upstream python-dracclient patch : [707138](https://review.opendev.org/#/c/707138/)
I have tested this patch locally by command. Please have a look.
-Rachit
=> Added Bus attribute for physical drives for nvme drives

src/pilot/assign_role.py
Hey @cdearborn , 
This PR is having implementation of auto-generation of Ceph OSD configuration for all including NVMe drives where execution of assign_role.py ensures that the required NVMe drives are also taken into configuration yaml file for Ceph installation instead of explicit mention in .properties file.
Tested this code on below configurations -
1. Storage node with HDDs and SSDs
2. Storage node with SSDs and NVMes
=> NVMe support in generation of Ceph-OSD configuration

src/pilot/dracclient_raid.patch
Hi Chris,
There was one typo error which was failing the deployment. It is resolved now. I also checked to upstream python-dracclient code which is clean. 
It was very hard to catch :)  Apologies..!
Rachit
=> Removed comma at the end of the line

src/pilot/dell_nfv.py
Empty DellComputeParameters section was causing YAQL expression error during overcloud deployment. Now this DellComputeParameters section will only be used when we are setting KernelArgs parameter.
=> YAQL expression parsing error fix

src/pilot/assign_role.py, src/pilot/dracclient_raid.patch, src/pilot/raid.patch
This PR merges in the following features from the experimental ironic branch:
1. Support for autogenerating the OSD configuration for NVMe drives
2. Moves code from assign_role into ironic using monkey patches.  This is so the monkey patches can be easily removed when the code appears in OSP.
=> Merge from ironic

src/deploy/osp_deployer/deployer.py, src/deploy/osp_deployer/settings/config.py
If some boolean node attributes are set to false instead of being omitted from the node configuration, the values are interpreted as True.  For instance if there is node configuration of:
{
"is_controller": "true",
"pxe_nic": "NIC.Integrated.1-3-1",
"idrac_ip": "192.168.110.13",
...
"skip_raid_config": "false",
"skip_nic_config": "false"
},
is node.skip_raid_config:  <- will be interpreted as true.
Fixed by using ternary operator in config.py so booleans are are always set to python booleans instead of strings:
try:
**node.skip_raid_config = (True if node.skip_raid_config
== "true" else False)**
except AttributeError:
node.skip_raid_config = False
pass
=> Fix node cfg bool attrs

src/pilot/client.patch, src/pilot/dracclient_raid.patch, src/pilot/dracclient_uris.patch, src/pilot/install-director.sh, src/pilot/utils.patch
Hey Chris,
I have added all the changes of two upstream patch as a monkey patch for python-dracclient below:
1. Add the ability to manage RAID settings : https://review.opendev.org/#/c/715172/
2. Fix for read-only and unchanged attributes:  https://review.opendev.org/#/c/722625/
I tested this monkey patches using command line but to be sure that it works, i started full deployment  on 71 stamp. Till then please do not merge this PR. 
After testing I will update and remove WIP on this PR.
Rachit
=> Added monkey patches for e-HBA feature and its bug fix

src/pilot/dracclient_raid.patch
Hi Chris,
There was minor error in monkey patch of dracclient/resource/raid.py.  In which old monkey patch creates two RAIDManagement class (i.e, instead of adding list_raid_settings() and set_raid_setting() method in existing RAIDManagement class, it creates new class.) 
This new monkey patch rectifies above error.
-Rachit
=> Fix RAIDManagement class in dracclient_raid patch

src/pilot/customize_image.sh
This patch removes the workaround for the T10PI issue since the
permanent fix has been released and verified in the HBA330 firmware
version 16.17.01.00.
Note that JetStream and Ironic users will need to upgrade the firmware
on their HBA330s to ensure that they do not encounter the T10PI issue
once this patch is merged.
=> Remove T10PI workaround

src/deploy/osp_deployer/director.py
Last edge patch incorrectly set cntlplane-subnet gateway to settings.provisioning_gateway, it should have remained settings.director_node.provisioning_ip
=> ctlplane-subnet gateway correction

src/pilot/templates/dell-environment.yaml
**NovaComputeExtraConfig:**
- live_migration_completion_timeout >> Default value is already 800, parameter not needed
- live_migration_progress_timeout >> Was documented as deprecated and last used in RHOSP14. Removed since OSP15
**ControllerExtraConfig:**
- osapi_max_limit >> Has been renamed to >> max_limit
- revocation_cache_time >> Was documented as deprecated and last used in RHOSP14. Removed since OSP15
=> Reviewed and updated extra-configs in dell-environment.yaml

src/pilot/templates/dell-environment.yaml, src/pilot/templates/first-boot.yaml
- rpc_response_timeout paramater is now used instead of sed commands in first-boot.yaml
- tuned profile is automatically applied by 'Tuned' service of Openstack and default "virtual-host" is defined in roles-data.yaml
=> Reviewed performance tunings in first-boot.yaml

src/pilot/templates/neutron-ovs-dpdk.yaml, src/pilot/templates/nic-configs/ovs-dpdk_6_port/controller.yaml, src/pilot/templates/nic-configs/ovs-dpdk_6_port/dellcompute_dpdk.yaml, src/pilot/templates/nic-configs/ovs-dpdk_6_port/nic_environment.yaml, src/pilot/templates/nic-configs/ovs-dpdk_6_port/storage.yaml, src/pilot/templates/nic-configs/ovs-dpdk_7_port/controller.yaml, src/pilot/templates/nic-configs/ovs-dpdk_7_port/dellcompute_dpdk.yaml, src/pilot/templates/nic-configs/ovs-dpdk_7_port/nic_environment.yaml, src/pilot/templates/nic-configs/ovs-dpdk_7_port/storage.yaml, src/pilot/templates/nic-configs/ovs-dpdk_8_port/controller.yaml, src/pilot/templates/nic-configs/ovs-dpdk_8_port/dellcompute_dpdk.yaml, src/pilot/templates/nic-configs/ovs-dpdk_8_port/nic_environment.yaml, src/pilot/templates/nic-configs/ovs-dpdk_8_port/storage.yaml, src/pilot/templates/nic-configs/ovs-dpdk_9_port/controller.yaml, src/pilot/templates/nic-configs/ovs-dpdk_9_port/dellcompute_dpdk.yaml, src/pilot/templates/nic-configs/ovs-dpdk_9_port/nic_environment.yaml, src/pilot/templates/nic-configs/ovs-dpdk_9_port/storage.yaml
- Heat Network Templates for OVS-DPDK deployment with RHOSP16.1
- Fixed typos and updated parameters for deployment
=> DPDK support for Rhosp 16.1, Heat/Nic Templates

src/deploy/osp_deployer/director.py, src/deploy/osp_deployer/settings/config.py, src/deploy/osp_deployer/settings/sample_csp_profile.ini, src/deploy/osp_deployer/settings/sample_hci_profile.ini, src/deploy/osp_deployer/settings/sample_xsp_profile.ini, src/pilot/deploy-overcloud.py, src/pilot/templates/dellemc-powermax-fc-cinder-backend.yaml, src/pilot/templates/dellemc-powermax-iscsi-cinder-backend.yaml, src/pilot/templates/dellemc-unity-cinder-backend.yaml, src/pilot/templates/dellemc-unity-cinder-container.yaml, src/pilot/templates/unity-manila-config.yaml, src/pilot/templates/unity-manila-container.yaml
1.	Unity Cinder – Deployed. The driver initialized successfully. Created and attached volumes using ISCSI.
2.	Unity Manila – Deployed. The driver initialized successfully. Share creation failed due to a defect in storops library. Pending a fix in the container
3.	Powermax Cinder – Deployed. The driver initialized successfully. Create volumes.
=> Unity and Powermax Fixes for 16.1

src/pilot/config_idrac.py
Clearing the job queue with FORCE causes a service internal to the iDRAC
to restart.  Until this service is fully up, information queried from
the iDRAC may not be complete. This patch changes config_idrac to
not use the FORCE option to resolve related issues.
=> Don't use FORCE when clearing the job queue

src/deploy/osp_deployer/director.py, src/deploy/osp_deployer/settings/sample_csp_profile.ini, src/deploy/osp_deployer/settings/sample_hci_profile.ini, src/deploy/osp_deployer/settings/sample_xsp_profile.ini, src/pilot/dell_nfv.py, src/pilot/templates/nic-configs/sriov_6_port_offload/controller.yaml, src/pilot/templates/nic-configs/sriov_6_port_offload/dellcompute_sriov.yaml, src/pilot/templates/nic-configs/sriov_6_port_offload/nic_environment.yaml, src/pilot/templates/nic-configs/sriov_6_port_offload/storage.yaml, src/pilot/templates/nic-configs/sriov_7_port_offload/controller.yaml, src/pilot/templates/nic-configs/sriov_7_port_offload/dellcompute_sriov.yaml, src/pilot/templates/nic-configs/sriov_7_port_offload/nic_environment.yaml, src/pilot/templates/nic-configs/sriov_7_port_offload/storage.yaml, src/pilot/templates/nic-configs/sriov_8_port_offload/controller.yaml, src/pilot/templates/nic-configs/sriov_8_port_offload/dellcompute_sriov.yaml, src/pilot/templates/nic-configs/sriov_8_port_offload/nic_environment.yaml, src/pilot/templates/nic-configs/sriov_8_port_offload/storage.yaml, src/pilot/templates/nic-configs/sriov_9_port_offload/controller.yaml, src/pilot/templates/nic-configs/sriov_9_port_offload/dellcompute_sriov.yaml, src/pilot/templates/nic-configs/sriov_9_port_offload/nic_environment.yaml, src/pilot/templates/nic-configs/sriov_9_port_offload/storage.yaml
- Support for sriov ovs-hw-offload in JS16.1
- Removes the additional dedicated NICs from Controller nodes for offload
- VF-LAG (SRIOV bonding) is implemented on compute nodes
- Has been tested for 6 port and 8 port deployments
=> SRIOV-Offload support, updates and templates

src/pilot/dell_nfv_edge.py
Re-organized a couple of lines so that kernel args gets picked up in case of sriov.
=> Fixed kernel-args for sriov on edge

src/deploy/osp_deployer/director.py, src/pilot/dell_nfv.py, src/pilot/deploy-overcloud.py, src/pilot/templates/dell-environment.yaml
During the deployment, timezone is not set on the overcloud nodes which can lead to inconsistency especially when it comes to ssl certificates.
This patch is for enabling the appropriate timezone which is set by default to America/Chicago but can be overwritten with a parameter within the .ini file.
=> fixing timezone on overcloud nodes

src/mgmt/osp-sah.ks
Some SAH node packages were broken including paramiko install.
Fix included and tested on R68. Good to go.
=> Fixed SAH node packages

src/deploy/jinja2_templates/neutron-ovs-dpdk-edge.j2.yaml, src/deploy/jinja2_templates/neutron-sriov-edge.j2.yaml, src/deploy/osp_deployer/director.py, src/pilot/dell_nfv_edge.py
This PR tracks all the updates and improvements from consulting sessions for edge.
1- Removed Scheduling filters from edge templates. They are only applied to core controllers.
2- Relocated Cpu parameters to make them role specific for Numa and DPDK deployments.
=> Updates for NFV at Edge

src/deploy/osp_deployer/director.py, src/deploy/osp_deployer/settings/sample_csp_profile.ini, src/deploy/osp_deployer/settings/sample_hci.ini, src/deploy/osp_deployer/settings/sample_powerflex.ini, src/deploy/osp_deployer/settings/sample_xsp_profile.ini
- Successfully deployed and tested **OVS-DPDK** on Broadcom with "**vfio-pci**" PMD driver (on R60)
- Minor Edge side NFV change
=> Edge & BCM related minor changes

src/deploy/jinja2_templates/nic-configs/compute_edge.j2.yaml
- Fixed the missing params in case of deploying Standalone SR-IOV 4 port at the Edge
- Cold Migration issue at Edge with SR-IOV is resolved.
Did multiple new SR-IOV deployments at Edge with this change, This PR is good to go.
=> CES-12022 Added missing params at Edge

src/pilot/assign_role.py
bin_physical_disks_by_size_gb method returns floating type value. 
It should return an int value.
=> Fix CES-11672 - bin_physical_disks_by_size_gb() returns floating point

src/deploy/osp_deployer/checkpoints.py, src/pilot/containers-prepare-parameter.yaml, src/pilot/deploy-overcloud.py, src/pilot/install-director.sh, src/pilot/kernelargs.patch, src/pilot/raid.patch, src/pilot/templates/roles_data.yaml
Hi,
This PR covers,
- raid.patch update for Latest Z6 release
- Added KernelArgs patch in case of NFV deployments on Z6
- Modified 8.8.8.8 to 10.8.8.8 (private DNS) in checkpoints for avoiding failures in deployments when 8.8.8.8 is blocked
- Updated image tag
FYI: This is fully tested on 14 G stamps with Z6, will test on 15G after virt-customize issue is resolved.
@gaelrehault Kindly review the PR and let me know if you have any concerns/comments?  Thanks
=> Patches updates for RHOSP 16.1 Z6 release
